services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686' # Web UI
      - '14250:14250' # gRPC for Jaeger-to-Jaeger communication
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./logs:/var/log # Monta el directorio local 'logs' como '/var/log' dentro del contenedor
    ports:
      - '4319:4317' # OTLP gRPC receiver
      - '4320:4318' # OTLP HTTP receiver
      - '8889:8889' # Prometheus exporter
    depends_on:
      - jaeger
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  logstash:
    user: root
    image: docker.elastic.co/logstash/logstash:7.14.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/var/log
    ports:
      - '5044:5044'
      - '9600:9600'
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - '3000:3000'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: techbankRootPsw
      MYSQL_DATABASE: futurex_course_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-ptechbankRootPsw']
      interval: 5s
      timeout: 3s
      retries: 10

  course-app:
    build:
      context: ./part0-JaegerCourseApp
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/futurex_course_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=techbankRootPsw
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - otel.exporter.otlp.endpoint=http://otel-collector:4317
    depends_on:
      mysql:
        condition: service_healthy
      otel-collector:
        condition: service_started

  course-catalog:
    build:
      context: ./part0-JaegerCourseCatalog
      dockerfile: Dockerfile
    ports:
      - '8002:8002'
    environment:
      - COURSE_SERVICE_URL=http://course-app:8001
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - otel.exporter.otlp.endpoint=http://otel-collector:4317
    depends_on:
      course-app:
        condition: service_started
      otel-collector:
        condition: service_started

volumes:
  mysql_data:
